apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "1.4.26"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: vault
      interval: 12h
  values:
    dataStorage:
      size: 5Gi
