apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2025.2.2"
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: authentik
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    authentik:
      secret_key: "${AUTHENTIK_KEY}"
      error_reporting:
        enabled: false
      postgresql:
        password: "${AUTHENTIK_POSTGRES_PASSWORD}"
    server:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "auth.dnsk.xyz"
        ingressClassName: external
        hosts:
          - &host "auth.dnsk.xyz"
    postgresql:
      enabled: true
      auth:
        password: "${AUTHENTIK_POSTGRES_PASSWORD}"
      primary:
        persistence:
          size: 4Gi
          storageClass: longhorn
    redis:
      enabled: true
      master:
        persistence:
          size: 1Gi
          storageClass: longhorn