---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "dnsk-xyz-production"
spec:
  secretName: "dnsk-xyz-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "dnsk.xyz"
  dnsNames:
    - "dnsk.xyz"
    - "*.dnsk.xyz"
